project:
  type: website
  output-dir: docs
  
website:
  title: "DONGQI LIN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - tools.qmd
    tools:
      - icon: github
        href: https://github.com/dongqi-DQ
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Dongqi Lin"

format:
  html:
    theme: cerulean
    toc: true

editor: source

